en:
  baseUrl: "https://lookee.how"

pt:
  baseUrl: "https://br.lookee.how"
  params:
    description: "coleção de artigos muito profissionais acerca de assuntos dos quais tenho muito conhecimento, escritos com altímissima habilidade"

    # home-info mode
    homeInfoParams:
      Title: "bem-vindo"
      Content: "à minha coleção de artigos muito profissionais acerca de assuntos dos quais tenho muito conhecimento, escritos com altímissima habilidade"

    editPost:
      Text: "Sugerir alterações" # edit text

  menu:
    main:
      #- identifier: categorias
      #  name: categorias
      #  url: /categorias/
      #  weight: 10
      - identifier: tags
        name: tags
        url: /tags/
        weight: 20
      - identifier: pesquisa
        name: pesquisar
        url: /pesquisa/
        weight: 30
    footer:
    - identifier: categorias
      name: categorias
      url: /categorias/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: pesquisar
      name: pesquisar
      url: /pesquisa/
      weight: 30

  taxonomies:
    categoria: categorias
    tag: tags

  # Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
  pygmentsUseClasses: true
  markup:
    highlight:
      noClasses: false
      # anchorLineNos: true
      # codeFences: true
      # guessSyntax: true
      # lineNos: true
      # style: monokai